---
title: "My Research"
---

<!-- Google Tag Manager -->
<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-NBK5N9D');</script>
<!-- End Google Tag Manager -->




In general, I'm deeply interested in measuring political attitudes and opinions primarily using dimensional scaling and machine learning. So far, my research has worked to better understand COVID attitudes and behaviors and the dimensionality of affective polarization. In the future, I aim to continue studying affective and ideological polarization in the United States (and elsewhere), and their interrelationship.


## Publications

- [Populism and the affective partisan space in nine European publics: Evidence from a cross-national survey](https://www.frontiersin.org/articles/10.3389/fpos.2022.984238/full)

- [Assessing the effectiveness of COVID-19 vaccine lotteries: A cross-state synthetic control methods approach](https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0274374)

- [The role of race and scientific trust on support for COVID-19 social distancing measures in the United States](https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0254127)

- [The Interactive Effects of Scientific Knowledge and Gender on COVID‐19 Social Distancing Compliance](https://onlinelibrary.wiley.com/doi/full/10.1111/ssqu.12894?casa_token=6e7Z-ZCUfysAAAAA%3A7yZfCaBB6TX6sbWXZlMGrZmmcDZlneO3w7sWqCka2PjzZCXBlOI7ghtgfxdz9DOPDZVwhv7wRajHJfi4)

- [The Conditional Effects of Scientific Knowledge & Gender on Support for COVID-19 Government Containment Policies in a Partisan America](https://www.cambridge.org/core/journals/politics-and-gender/article/conditional-effect-of-scientific-knowledge-and-gender-on-support-for-covid19-government-containment-policies-in-a-partisan-america/C4AEB27D4046433749A883941AC74809)


## Working Papers

- See It in 3D: The Underlying Dimensions of Affective Polarization

- [Towards a General Methodology of Bridging Ideological Spaces](https://www.researchgate.net/publication/343736604_Towards_a_General_Methodology_of_Bridging_Ideological_Spaces)

- Progressives and Never-Trumpers: Contrastive Principal Component Analysis as an Alternative Method for Public Opinion Research

- Rational Voting in the Age of Ideological Polarization & Responsible Parties: Examining Presidential Elections from 1972–2020